### ISSUE TITLE
differences

### ISSUE THREAD

**Issue by johanneswilm** [duncaningram/django-fixture-media#2]
And which one is recommended?

This app, https://github.com/shockflash/mediafixtures or https://github.com/leetrout/django-fixturemedia

**Comment by markpasc** [comment]
There certainly are a bunch of media fixture apps! I'm not sure I saw those particular ones, but I did look at several before writing this one. Few (maybe none) of the ones I saw:
- provide a way to _dump_ a fixture with media files, so you'd have to copy the appropriate files into a `fixtures/media/` tree manually
- wrap the existing `loaddata` command, instead requiring a separate, easily forgettable step when loading fixtures
- load only referenced media files, so as not to load files into a project for a fixture you didn't load

A simpler media fixture loader is great for most people probably, but that's why I wrote yet another one instead. HTH!

**Comment by johanneswilm** [comment]
ok, you convinced me. Your's seems like the cleanest approach there is.
